const resObj = [
    {
      id: 1,
      name: "Hashtag Foods",
      adress: "148 Queen St E, Brampton",
      restaurantPoint: "3.8",
      status: "excellent",
      minimumPrice: "$25.0",
      deliveryCost: "5.0$",
      restaurantImageUrl: "https://i.ibb.co/PDP6QN9/imageedit-2-8913973589.jpg",
    },
    {
      id: 2,
      name: "McDonalds",
      adress: "Sandawood Plaza, Brampton",
      restaurantPoint: "3.5",
      status: "good",
      minimumPrice: "15.0$",
      deliveryCost: "10.0$",
      restaurantImageUrl: "https://i.ibb.co/C09njxC/imageedit-4-3775173323.jpg",
    },
    {
      id: 3,
      name: "Pizza Point",
      adress: "Conestoga Square, Brampton",
      restaurantPoint: "3.3",
      status: "bad",
      minimumPrice: "50.0$",
      deliveryCost: "0.0$",
      restaurantImageUrl: "https://i.ibb.co/CQZ8Nb6/imageedit-6-8890698964.jpg",
    },
    {
      id: 4,
      name: "Lazeez Shawrma",
      adress: "Steeles & Kennedy",
      restaurantPoint: "4.7",
      status: "excellent",
      minimumPrice: "100.0$",
      deliveryCost: "10.0$",
      restaurantImageUrl: "https://i.ibb.co/kMkm8qZ/imageedit-8-6584922246.jpg",
    },
    {
      id: 5,
      name: "Burger King",
      adress: "123 University Avenue, Waterloo ",
      restaurantPoint: "4.3",
      status: "bad",
      minimumPrice: "35.0$",
      deliveryCost: "10.0$",
      restaurantImageUrl: "https://i.ibb.co/7vvrxwz/imageedit-10-4852470901.jpg",
    },
    {
      id: 6,
      name: "RK Nutri Kulcha",
      adress: "Sabji mandi, Kapurthala",
      restaurantPoint: "4.5",
      status: "good",
      minimumPrice: "10.0$",
      deliveryCost: "0.0$",
      restaurantImageUrl: "https://i.ibb.co/PcKPSX9/imageedit-12-5594272064.jpg",
    },
  ];
  
  export default resObj;